;; marc-mode.el
;; see deform-mode
(defvar top-keywords '(
"title"
"elements"
"end"
"end option"
"continue"
"rezone"
"end rezone"
))

(defvar parameters
'("ablation"
"accumulate"
"acoustic"
"adaptive"
"alias"
"all points"
"allocate"
"appbc"
"assumed strain"
"automset"
"autospc"
"beam sect"
"bearing"
"boundary conditions"
"buckle"
"cavity"
"centroid"
"co_sim"
"comment"
"constant dilatation"
"couple"
"creep"
"curing"
"decoupling"
"design optimization"
"design sensitivity"
"diffusion"
"dist loads"
"dynamic"
"elastic"
"elasticity"
"electro"
"elements"
"el-ma"
"elsto"
"end"
"extended"
"feature"
"films"
"finite"
"fluid"
"fluxes"
"follow for"
"fourier"
"harmonic"
"heat"
"ibooc"
"include"
"input tape"
"io-deactivate"
"istress"
"joule"
"large disp"
"large strain"
"linear"
"load cor"
"lump"
"machining"
"magneto"
"mnf"
"mpc-check"
"new"
"no echo"
"no loadcor"
"piezo"
"plasticity"
"pore"
"prealloc"
"print"
"processor"
"pyrolysis"
"radiation"
"rbe"
"response"
"restrictor"
"rezoning"
"r-p flow"
"scale"
"shell sect"
"sizing"
"spflow"
"ss-rolling"
"state vars"
"stop"
"structural"
"super"
"table"
"thermal"
"tie"
"title"
"tshear"
"t-t-t"
"unit"
"update"
"user"
"version"
"viscelharm"
"visco elas"
"welding"))
(defvar model-definition-options '(
"ACOUSTIC"
"ACTUATOR"
"ADAPT GLOBAL"
"ADAPTIVE"
"ANISO HYPE"
"ANISOTROPIC"
"ANNEAL PROP"
"ARRUDBOYCE"
"ARRUDBOYCE"
"ATTACH EDGE"
"ATTACH FACE"
"ATTACH NODE"
"AXITO3D"
"B2GG"
"B2PP"
"BACKTOSUBS"
"BERGBOYCE"
"B-H RELATION"
"BLOCKS"
"BOUNDARY"
"BSQUEAL"
"BUCKLE INCREMENT"
"CASE COMBIN"
"CAVITY DEFINITION"
"CAVITY"
"CFAST"
"CHANGE PORE"
"CHANGE STATE"
"CHANNEL"
"COEFFICIENT"
"COHESIVE"
"COIL CURRENT"
"COMPOSITE"
"CON INTERA"
"CON TABLE"
"CONM1"
"CONM2"
"CONN FILL"
"CONN GENER"
"CONNECT"
"CONNECTIVITY"
"CONRAD GAP"
"CONSTRAINT"
"CONTACT"
"CONTACT NODE"
"CONTACT TABLE"
"CONTROL"
"CONUDS"
"CONVERT"
"COORD SYSTEM"
"COORDINATES"
"CORNERING AXIS"
"COUPLE CONTROL"
"COUPLING REGION"
"CRACK DATA"
"CRACK INIT"
"CREATE SEC"
"CREEP"
"CURE RATE"
"CURE SHRINKAGE"
"CURVES"
"CWELD"
"CYCLIC SYMMETRY"
"CYLINDRICAL"
"DAMAGE"
"DAMPING"
"DEACT GLUE"
"DEACTIVATE"
"DEFINE"
"DELAMINATION"
"DENSITY EFFECTS"
"DESIGN DISPLACEMENT CONSTRAINTS"
"DESIGN FREQUENCY CONSTRAINTS"
"DESIGN OBJECTIVE"
"DESIGN STRAIN CONSTRAINTS"
"DESIGN STRESS CONSTRAINTS"
"DESIGN VARIABLES"
"DIST CHARGE"
"DIST CHARGES"
"DIST CURRENT"
"DIST FLUXES"
"DIST LOADS"
"DIST MASS"
"DIST SOURCES"
"DMIG"
"DMIG-OUT"
"ELEMENT SORT"
"EMCIRCUIT"
"EMISSIVITY"
"EMWINDING"
"END OPTION"
"ERROR ESTIMATE"
"EXCLUDE"
"EXPORT SEC"
"FACE IDS"
"FAIL DATA"
"FILMS"
"FIXED ACCE"
"FIXED DISP"
"FIXED EL-POT"
"FIXED MG-POT"
"FIXED POTENTIAL"
"FIXED PRESSURE"
"FIXED TEMPERATURE"
"FIXED VELOCITY"
"FIXED VOLTAGE"
"FLOW LINE"
"FLUID DRAG"
"FLUID SOLID"
"FOAM"
"FORCDT"
"FORMING LIMIT"
"FOUNDATION"
"FOURIER"
"FXORD"
"GAP DATA"
"GASKET"
"GENERATE"
"GENT"
"GEOMETRY"
"GLK"
"GLOBALLOCAL"
"GRAIN SIZE"
"GRID FORCE"
"HOLD NODES"
"HYPERMESH"
"HYPOELASTIC"
"IMPORT SEC"
"INCLUDE"
"INERTIA RELIEF"
"INIT CURE"
"INIT STRESS"
"INITIAL DATA"
"INITIAL DENSITY"
"INITIAL DISP"
"INITIAL FICTIVE"
"INITIAL PC"
"INITIAL PLASTIC STRAIN"
"INITIAL PORE"
"INITIAL POROSITY"
"INITIAL PYROLYSIS"
"INITIAL STATE"
"INITIAL TEMP"
"INITIAL VEL"
"INITIAL VOID RATIO"
"INSERT"
"IRM"
"ISLAND REMOVAL"
"ISOTROPIC"
"J-INTEGRAL"
"JOULE"
"K2GG"
"K2PP"
"LATENT HEAT"
"LOADCASE"
"LORENZI"
"M2GG"
"M2PP"
"MANY TYPES"
"MAP TEMP"
"MAPPER"
"MARLOW"
"MASSES"
"MATERIAL DATA"
"MATUDS"
"MERGE"
"MERGE SELECTIVE"
"MESH2D"
"MICROSTRUCTURE"
"MIXTURE"
"MNF UNITS"
"MODAL INCREMENT"
"MOONEY"
"MPCOUT"
"NEW"
"NLELAST"
"NO ELEM SORT"
"NO NODE SORT"
"NO PRINT"
"NO PRINT CONTACT"
"NO PRINT SPRING"
"NO SUMMARY"
"NODAL THICKNESS"
"NODE CIRCLE"
"NODE FILL"
"NODE GENER"
"NODE MERGE"
"NODE SORT"
"OGDEN"
"OP2"
"OPTIMIZE"
"ORIENTATION"
"ORTHO TEMP"
"ORTHOTROPIC"
"P2G"
"PARAMETERS"
"PAYNE"
"PBUSH"
"PERM SET"
"PERMANENT"
"PFAST"
"PHI-COEFFICIENTS"
"PIEZOELECTRIC"
"PIN CODE"
"POINT CHARGE"
"POINT CURRENT"
"POINT CURRENT-CHARGE"
"POINT FLUX"
"POINT LOAD"
"POINT MASS"
"POINT SOURCE"
"POINT TEMP"
"POINTS"
"POROSITY CHANGE"
"POST"
"POWDER"
"PRE STATE"
"PRESS FILM"
"PRINT CHOICE"
"PRINT CONTACT"
"PRINT ELEMENT"
"PRINT NODE"
"PRINT NODSTS"
"PRINT SPRING"
"PRINT STREAMLINE"
"PRINT VMASS"
"PRTCONNECT"
"PSHELL"
"PWELD"
"QVECT"
"RAD-CAVITY"
"RADIATING CAVITY"
"RBE2"
"RBE3"
"READ MATERIAL"
"REAUTO"
"REBAR"
"RECEDING SURFACE"
"REGION"
"RELATIVE DENSITY"
"RESPONSE SPECTRUM"
"RESTART LAST"
"RESTART"
"RESTRICTOR"
"RIGID NODE"
"ROTATION A"
"RROD"
"SDRC"
"SERVO LINK"
"SHAPE MEMORY"
"SHELL TRANSFORMATION"
"SHIFT FUNCTION"
"SINK POINTS"
"SOIL"
"SOLVER"
"SPECIFIC WEIGHT"
"SPECIFIED NODES"
"SPLINE"
"SPRINGS"
"START NUMBER"
"STIFSCALE"
"STRAIN RATE"
"STREAM DEFINITION"
"STRING"
"SUMMARY"
"SUPERELEM"
"SURFACE ENERGY"
"SURFACES"
"SWLDPRM"
"SYMMETRY"
"TABLE"
"TEMPERATURE EFFECTS"
"TERM CURRENT"
"TERM VOLTAGE"
"THERMAL CONTACT"
"THERMAL LOADS"
"THERMO-PORE"
"THICKNESS"
"THROAT"
"TIME-TEMP"
"TRACK STREAMLINE"
"TRACK"
"TRANSFORMATION"
"TYING"
"UDUMP"
"UFCONN"
"UFRICTION"
"UFXORD"
"UHTCOEF"
"UHTCON"
"UMOTION"
"USDATA"
"UTRANFORM"
"VCCT"
"VELOCITY"
"VIEW FACTOR"
"VISCEL EXP"
"VISCELCORR"
"VISCELFOAM"
"VISCELMOON"
"VISCELOGDEN"
"VISCELORTH"
"VISCELPROP"
"VISCO HYPE"
"VISCOCREEP"
"VOID CHANGE"
"WEAR"
"WELD FILL"
"WELD FLUX"
"WELD PATH"
"WORK HARD"
"WRITE"))

(defun add-prefix (string)
  (concat "^" string))

(defvar parameters-regexp
  (mapconcat 'add-prefix parameters "\\|"))

(defvar model-definition-options-regex
  (mapconcat 'add-prefix model-definition-options "\\|"))

(defvar parameters-regexp
  (mapconcat 'add-prefix parameters "\\|"))

(defvar top-keywords-regexp
  (mapconcat 'add-prefix top-keywords "\\|"))

(defvar marc-font-lock-defaults
  `((
   ("^//$ " . font-lock-comment-face)
   (,parameters-regexp . font-lock-preprocessor-face)
   (,model-definition-options-regex . font-lock-keyword-face)
   ("^[ \t]+$" . highlight)
  )))

(defvar marc-mode-hook nil)

(defvar marc-ruler "**..:....1....:....2....:....3....:....4....:....5....:....6....:....7....:....8"
  "*The ruler `marc-insert-ruler' inserts."
)

(defun marc-insert-ruler ()
  "Insert a ruler with comments."
  (interactive)
  (end-of-line)  
  (insert marc-ruler)
)

(defvar marc-comment-prefix "$"
  "*The comment `marc-insert-comment' inserts."
)

(define-derived-mode marc-mode fundamental-mode "marc input file"
    ;; for comments
    ;; overriding these vars gets you what (I think) you want
    ;; they're made buffer local when you set them
    (setq font-lock-defaults marc-font-lock-defaults)
    (setq comment-start "$ ")
    (setq comment-end "")
    ;; example heading
    ;; *  Process Definition
    (setq require-final-newline  t)
    (run-mode-hooks 'marc-mode-hook))

(defun non-alphabet-outline ()
    (setq-local outline-minor-mode-hook nil)
    (outline-minor-mode t)
    (setq outline-level (lambda()
           (let* ((data (match-data))
                  (start (car data))
                  (end (cadr data))
                  (level (- end start)))
             (cond ((looking-at "\\$ [*]\\{1,8\\} ") (- level 1))
                   ((looking-at `,top-keywords-regexp) 1)
                   ((looking-at "\\$ [a-zA-Z]+.*") 1)
                   ((looking-at `,parameters-regexp) 12)
                   (t 34))))
          outline-regexp "\\$ [a-zA-Z]+.*\\|\\$ [*]\\{1,8\\} \\|^[a-zA-Z]+.*"))

(add-hook 'marc-mode-hook 'non-alphabet-outline)

(provide 'marc-mode)
